### ISSUE TITLE
Migrate application databases 

### ISSUE THREAD

**Issue by carlosadean** [linea-it/idac_data#3]
```[tasklist]
### Tasks - Phase 1
- [ ] Migrate the legacy databases from the old servers
```

```[tasklist]
### Tasks - Phase 2
- [ ] Create a list of applications which DBs are running on docker
- [ ] Migrate the databases from docker to the new Postgres servers
```
